name: .NET Framework Desktop

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore ISBoxerEVELauncher.sln

    - name: Build solution
      run: msbuild ISBoxerEVELauncher.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Package release artifacts
      run: Compress-Archive -Path bin/Release/* -DestinationPath ISBoxerEVELauncher-Release.zip

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./ISBoxerEVELauncher-Release.zip
        asset_name: ISBoxerEVELauncher-Release.zip
        asset_content_type: application/zip
